version: "3.7"
services:

  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    env_file:
      - .env
    image: mikemkbnv/grpc-web-envoy
    ports:
      - "8080:8080"
    links:
      - access-server

  access-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: mikemkbnv/grpc-web-access
    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis
    volumes:
      - /Users/mkkbnv/go/src/grpc-react-web/images:/app/data

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: mikemkbnv/grpc-web-react
    ports:
      - "3000:3000"
    # links:
    #   - envoy
  face-recognition:
    build:
      context: ./face-recognition
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - redis
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres-db: