/**
 * @fileoverview gRPC-Web generated client stub for access
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: echo.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.access = require('./echo_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.access.AccessClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.access.AccessPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.access.EntranceRequest,
 *   !proto.access.Response>}
 */
const methodDescriptor_Access_AccessCheck = new grpc.web.MethodDescriptor(
  '/access.Access/AccessCheck',
  grpc.web.MethodType.UNARY,
  proto.access.EntranceRequest,
  proto.access.Response,
  /**
   * @param {!proto.access.EntranceRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.access.Response.deserializeBinary
);


/**
 * @param {!proto.access.EntranceRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.access.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.access.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.access.AccessClient.prototype.accessCheck =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/access.Access/AccessCheck',
      request,
      metadata || {},
      methodDescriptor_Access_AccessCheck,
      callback);
};


/**
 * @param {!proto.access.EntranceRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.access.Response>}
 *     Promise that resolves to the response
 */
proto.access.AccessPromiseClient.prototype.accessCheck =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/access.Access/AccessCheck',
      request,
      metadata || {},
      methodDescriptor_Access_AccessCheck);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.access.ExitRequest,
 *   !proto.access.Response>}
 */
const methodDescriptor_Access_ExitCheck = new grpc.web.MethodDescriptor(
  '/access.Access/ExitCheck',
  grpc.web.MethodType.UNARY,
  proto.access.ExitRequest,
  proto.access.Response,
  /**
   * @param {!proto.access.ExitRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.access.Response.deserializeBinary
);


/**
 * @param {!proto.access.ExitRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.access.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.access.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.access.AccessClient.prototype.exitCheck =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/access.Access/ExitCheck',
      request,
      metadata || {},
      methodDescriptor_Access_ExitCheck,
      callback);
};


/**
 * @param {!proto.access.ExitRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.access.Response>}
 *     Promise that resolves to the response
 */
proto.access.AccessPromiseClient.prototype.exitCheck =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/access.Access/ExitCheck',
      request,
      metadata || {},
      methodDescriptor_Access_ExitCheck);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.access.EmployeeRequest,
 *   !proto.access.EmployeeResponse>}
 */
const methodDescriptor_Access_AddEmployee = new grpc.web.MethodDescriptor(
  '/access.Access/AddEmployee',
  grpc.web.MethodType.UNARY,
  proto.access.EmployeeRequest,
  proto.access.EmployeeResponse,
  /**
   * @param {!proto.access.EmployeeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.access.EmployeeResponse.deserializeBinary
);


/**
 * @param {!proto.access.EmployeeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.access.EmployeeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.access.EmployeeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.access.AccessClient.prototype.addEmployee =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/access.Access/AddEmployee',
      request,
      metadata || {},
      methodDescriptor_Access_AddEmployee,
      callback);
};


/**
 * @param {!proto.access.EmployeeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.access.EmployeeResponse>}
 *     Promise that resolves to the response
 */
proto.access.AccessPromiseClient.prototype.addEmployee =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/access.Access/AddEmployee',
      request,
      metadata || {},
      methodDescriptor_Access_AddEmployee);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.access.DeleteEmployeeRequest,
 *   !proto.access.EmptyResponse>}
 */
const methodDescriptor_Access_DeleteEmployee = new grpc.web.MethodDescriptor(
  '/access.Access/DeleteEmployee',
  grpc.web.MethodType.UNARY,
  proto.access.DeleteEmployeeRequest,
  proto.access.EmptyResponse,
  /**
   * @param {!proto.access.DeleteEmployeeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.access.EmptyResponse.deserializeBinary
);


/**
 * @param {!proto.access.DeleteEmployeeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.access.EmptyResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.access.EmptyResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.access.AccessClient.prototype.deleteEmployee =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/access.Access/DeleteEmployee',
      request,
      metadata || {},
      methodDescriptor_Access_DeleteEmployee,
      callback);
};


/**
 * @param {!proto.access.DeleteEmployeeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.access.EmptyResponse>}
 *     Promise that resolves to the response
 */
proto.access.AccessPromiseClient.prototype.deleteEmployee =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/access.Access/DeleteEmployee',
      request,
      metadata || {},
      methodDescriptor_Access_DeleteEmployee);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.access.EmptyRequest,
 *   !proto.access.ListEmployeesResponse>}
 */
const methodDescriptor_Access_ListEmployees = new grpc.web.MethodDescriptor(
  '/access.Access/ListEmployees',
  grpc.web.MethodType.UNARY,
  proto.access.EmptyRequest,
  proto.access.ListEmployeesResponse,
  /**
   * @param {!proto.access.EmptyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.access.ListEmployeesResponse.deserializeBinary
);


/**
 * @param {!proto.access.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.access.ListEmployeesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.access.ListEmployeesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.access.AccessClient.prototype.listEmployees =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/access.Access/ListEmployees',
      request,
      metadata || {},
      methodDescriptor_Access_ListEmployees,
      callback);
};


/**
 * @param {!proto.access.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.access.ListEmployeesResponse>}
 *     Promise that resolves to the response
 */
proto.access.AccessPromiseClient.prototype.listEmployees =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/access.Access/ListEmployees',
      request,
      metadata || {},
      methodDescriptor_Access_ListEmployees);
};


module.exports = proto.access;

