/**
 * @fileoverview gRPC-Web generated client stub for access
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: echo.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.access = require('./echo_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.access.AccessClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.access.AccessPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.access.AccessRequest,
 *   !proto.access.AccessResponse>}
 */
const methodDescriptor_Access_AccessCheck = new grpc.web.MethodDescriptor(
  '/access.Access/AccessCheck',
  grpc.web.MethodType.UNARY,
  proto.access.AccessRequest,
  proto.access.AccessResponse,
  /**
   * @param {!proto.access.AccessRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.access.AccessResponse.deserializeBinary
);


/**
 * @param {!proto.access.AccessRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.access.AccessResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.access.AccessResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.access.AccessClient.prototype.accessCheck =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/access.Access/AccessCheck',
      request,
      metadata || {},
      methodDescriptor_Access_AccessCheck,
      callback);
};


/**
 * @param {!proto.access.AccessRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.access.AccessResponse>}
 *     Promise that resolves to the response
 */
proto.access.AccessPromiseClient.prototype.accessCheck =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/access.Access/AccessCheck',
      request,
      metadata || {},
      methodDescriptor_Access_AccessCheck);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.access.AccessRequest,
 *   !proto.access.AccessResponse>}
 */
const methodDescriptor_Access_Echo = new grpc.web.MethodDescriptor(
  '/access.Access/Echo',
  grpc.web.MethodType.UNARY,
  proto.access.AccessRequest,
  proto.access.AccessResponse,
  /**
   * @param {!proto.access.AccessRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.access.AccessResponse.deserializeBinary
);


/**
 * @param {!proto.access.AccessRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.access.AccessResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.access.AccessResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.access.AccessClient.prototype.echo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/access.Access/Echo',
      request,
      metadata || {},
      methodDescriptor_Access_Echo,
      callback);
};


/**
 * @param {!proto.access.AccessRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.access.AccessResponse>}
 *     Promise that resolves to the response
 */
proto.access.AccessPromiseClient.prototype.echo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/access.Access/Echo',
      request,
      metadata || {},
      methodDescriptor_Access_Echo);
};


module.exports = proto.access;

